/*
Kávéfőző bekapcsolása
IF NINCS ELÉG KÁVÉ THEN
|   KÁVÉ HOZZÁADÁSA
ENDIF
IF NINCS ELÉG VÍZ THEN
|   VÍZ HOZZÁADÁSA
ENDIF
WHILE NEM MELEGETETT FEL
|   10 MP VÁRAKOZÁS
ENDWHILE
CSÉSE ODAHELYEZÉSE
GOMB MEGNYOMÁSA
*/